### ISSUE TITLE
How to convert seed to Mnemonic?

### ISSUE THREAD

**Issue by ianeinser** [Soneso/stellar_flutter_sdk#12]
Hi,

is there any function / method to convert seed to Mnemonic?

Regards,

Ian

**Comment by christian-rogobete** [comment]
Hi Ian,
there is no way convert a seed into a mnemonic.
Best Christian

**Comment by AliKarimiENT** [comment]
Hello Christian
I wanna get account id and secret seed from mnemonic
Is it possible? 
I have created a wallet and I need to load user's data with these phrases
Thanks

**Comment by christian-rogobete** [comment]
Hi @AliKarimiENT 
sure, look at this sdk example:
https://github.com/Soneso/stellar_flutter_sdk/blob/master/documentation/sdk_examples/sep-0005-key-derivation.md#generate-key-pairs-from-mnemonic
hope this helps!
