### ISSUE TITLE
Handling the notification for payment receive

### ISSUE THREAD

**Issue by xvilaysouk** [Soneso/stellar_flutter_sdk#15]
Thank you very much for the great work!

I have a question regarding how to handle the notification when the payment is received?

**Comment by christian-rogobete** [comment]
Hey @xvilaysouk yw.

There is an example for streaming for payments: https://github.com/Soneso/stellar_flutter_sdk/blob/master/documentation/sdk_examples/stream_payments.md

However, this only works if your app is running. If you want to implement notifications even if the app is currently not open (or running in the background) on the device, than you will need to implement that on server side and send push notifications to your app.

Hope this helps.

Kind regards
Christian

**Comment by xvilaysouk** [comment]
Thanks Christian for your reply.

Sincerely yours,
X. Vilaysouk
