### ISSUE TITLE
accepting other known assets

### ISSUE THREAD

**Issue by yawebs** [Soneso/stellar_flutter_sdk#16]
Hi, am Christian From Zegital Development firm in Nigeria.
i just embarked on the journey of implementing and using Stellar for my clients apps
and i really need ur help in answering this one question.
Can my clients buy and store stable coins like usdt or usdc in there wallet? can they also have other assets like bitcoin and etherum? if yes please how to i go about this
i have started the development process already for the app, and also integrated Stellar sdk, i just need this questions aswered and directions, thanks

**Comment by christian-rogobete** [comment]
Hi @yawebs,
thank you for your message. The stellar flutter sdk supports only assest based on the stellar network. Using the sdk you can provide functionality in your wallet that allows your users to trust such assets. You can also provide functionality to trade trusted assets by managing buy and sell offers.
Hope this answer helps you. For more information on assets based on the stellar network please read the docs provided by stellar.org.
Kind regards
Christian
