### ISSUE TITLE
Support for Flutter 2

### ISSUE THREAD

**Issue by martinloesethjensen** [Soneso/stellar_flutter_sdk#17]
Hi 👋 It would be very nice to have the package support Flutter 2 and have it [migrated to null-safety](https://dart.dev/null-safety/migration-guide)

**Comment by christian-rogobete** [comment]
Hi @martinloesethjensen, 

thank you for your message and for your suggestion. We will implement it as soon as the dependent packages are migrated. I will let you know as soon as ready.

Kind regards
Christian

**Comment by martinloesethjensen** [comment]
Awesome thanks 🚀 @christian-rogobete
