### ISSUE TITLE
buying popular coins like bitcoin, ethereum and others

### ISSUE THREAD

**Issue by yawebs** [Soneso/stellar_flutter_sdk#20]
have been following the whole guild on flutter but still cant figure out how to create a buy offer for already existing tokens like bitcoin, ethereum,xrp and others, please i need a guide on these

**Comment by christian-rogobete** [comment]
Hey @yawebs you can only trade assets on the stellar network. Normally you do so by using anchors. They offer different assets like bitcoin or fiat currencies on the stellar network in form of stellar assets. Please have a look to this video that explains the concept of anchors:
https://www.youtube.com/watch?v=9iN9XT1rHHA
You can find different anchors listed here:
https://steexp.com/anchors
Please also read the official stellar documentation to find out more about the concept of anchors and assets on the stellar network. With this SDK you can create buy offers as described here:
https://github.com/Soneso/stellar_flutter_sdk/blob/master/documentation/sdk_examples/manage_buy_offer.md
