### ISSUE TITLE
Update Http to the latest

### ISSUE THREAD

**Issue by delrioe** [Soneso/stellar_flutter_sdk#25]
Because every version of stellar_flutter_sdk depends on http ^0.12.0+3 and mayan depends on http ^0.13.3, stellar_flutter_sdk is forbidden.

**Comment by christian-rogobete** [comment]
Thank you @delrioe, updated in [release 1.2.0](https://github.com/Soneso/stellar_flutter_sdk/releases/tag/1.2.0)
