### ISSUE TITLE
Unable to sign transaction using example

### ISSUE THREAD

**Issue by torkel** [Soneso/stellar_flutter_sdk#31]
I get 
"Unsupported operation: Int64 accessor not supported by dart2js."
When trying to sign an transaction using example at:
https://github.com/Soneso/stellar_flutter_sdk/blob/master/documentation/sdk_examples/send_native_payment.md
Error is in browser_client.dart, row 58 in http lib
completer.complete(StreamedResponse(

Using Flutter 2.5.1
stellar_flutter_sdk: ^1.2.1
Visual Studio Code 1.60.1 on Windows 10.
Flutter extension: 3.26.0

Using Network.TESTNET and StellarSDK.TESTNET;
Fetching account information works but not signing a transaction.
Have created and funded two separate accounts on TESTNET just to test but without luck.
Tested the same transaction with Stellar Laboratory and it works.
Fairly new to flutter but have done a couple of project using the go client for Stellar.

**Comment by christian-rogobete** [comment]
Hello @torkel, unfortunately the sdk is not working with flutter web.

**Comment by AliKarimiENT** [comment]
> Hello @torkel, unfortunately the sdk is not working with flutter web.

Hello Christian
We need to use flutter web also for our project but these errors don't allow us to use it. Why this SDK is not working for flutter web? There is no chance that we will have it as soon as possible?

**Comment by AliKarimiENT** [comment]
@christian-rogobete 
Please help me 🙏🌹

**Comment by christian-rogobete** [comment]
Hello @AliKarimiENT, unfortunately I can not help you with this. It is not working with flutter web because the code and libraries used can not be used on flutter web. Maybe some day as flutter web gets more advanced it will work. For now I recommend you to use the js sdk for web.

**Comment by AliKarimiENT** [comment]
> Hello @AliKarimiENT, unfortunately I can not help you with this. It is not working with flutter web because the code and libraries used can not be used on flutter web. Maybe some day as flutter web gets more advanced it will work. For now I recommend you to use the js sdk for web.

Yes, thanks for your response
Actually I don't know js and I'm a flutter developer.
Now , some parts work correctly but in some parts I face some unknown issues .
Is it a good idea that I use direct APIs instead of using the SDK ? Does this help me to achieve my goal or not?

**Comment by christian-rogobete** [comment]
Depends on what you want to do. If you need to sign transactions you will not be able to do it with API calls. I think that the best idea is to learn and use the js sdk. Especially if you want to sign in the client and not send or store secret keys to/on the server.
