### ISSUE TITLE
Create key pair from account id is malfunctioning?

### ISSUE THREAD

**Issue by Sotatek-DatThai** [Soneso/stellar_flutter_sdk#33]
Hi! 
I use `KeyPair.fromAccountId(accountId)` to get key pair.
But i can't sign transaction with this keypair.
How can i sign xdr with another account id?

**Comment by christian-rogobete** [comment]
Hi @Sotatek-DatThai , one can not sign with an accountId (it is only a public key). You need the seed to be able to sign.
