### ISSUE TITLE
Transaction.fromEnvelopeXdrString failing to parse XDR

### ISSUE THREAD

**Issue by flyweight** [Soneso/stellar_flutter_sdk#35]
The following code throws an unknown enum value exception. Any ideas what I'm missing?

```dart
AbstractTransaction.fromEnvelopeXdrString('AAAAAgAAAABGmZyYeYjKxpmwZv1hTKWY5Uc5pzHr7Ld2Tg9KZlXJ2gAAnEAAA588AAAAAwAAAAAAAAABAAAACVBVUnxSVURZMgAAAAAAAAQAAAABAAAAAIw4P8JGqI0p0eawiPOSVAgxDEoyfX71XxIuCEWAAtgeAAAAEAAAAABGmZyYeYjKxpmwZv1hTKWY5Uc5pzHr7Ld2Tg9KZlXJ2gAAAAEAAAAAWN3OP2d8s6y4UvUHUsTnvMLoMY9GcBsYEZA/jVvq5l8AAAABAAAAAEaZnJh5iMrGmbBm/WFMpZjlRzmnMevst3ZOD0pmVcnaAAAAAlVTRFBFTkQAAAAAAAAAAABY3c4/Z3yzrLhS9QdSxOe8wugxj0ZwGxgRkD+NW+rmXwAAAAAF9eEAAAAAAQAAAABGmZyYeYjKxpmwZv1hTKWY5Uc5pzHr7Ld2Tg9KZlXJ2gAAAA4AAAACVVNEUEVORAAAAAAAAAAAAFjdzj9nfLOsuFL1B1LE57zC6DGPRnAbGBGQP41b6uZfAAAAAAX14QAAAAACAAAAAAAAAABGmZyYeYjKxpmwZv1hTKWY5Uc5pzHr7Ld2Tg9KZlXJ2gAAAAAAAAAAAAAAAFjdzj9nfLOsuFL1B1LE57zC6DGPRnAbGBGQP41b6uZfAAAAAwAAAAEAAAAEAAAAAGGedecAAAABAAAAAEaZnJh5iMrGmbBm/WFMpZjlRzmnMevst3ZOD0pmVcnaAAAAEQAAAAAAAAAA');
```

Exception:

```
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: Exception: Unknown enum value: 1637774823
#0      XdrClaimPredicateType.decode (package:stellar_flutter_sdk/src/xdr/xdr_ledger.dart:136:9)
#1      XdrClaimPredicate.decode (package:stellar_flutter_sdk/src/xdr/xdr_ledger.dart:226:64)
#2      XdrClaimPredicate.decode (package:stellar_flutter_sdk/src/xdr/xdr_ledger.dart:236:57)
#3      XdrClaimPredicate.decode (package:stellar_flutter_sdk/src/xdr/xdr_ledger.dart:248:50)
#4      XdrClaimantV0.decode (package:stellar_flutter_sdk/src/xdr/xdr_ledger.dart:350:43)
#5      XdrClaimant.decode (package:stellar_flutter_sdk/src/xdr/xdr_ledger.dart:319:36)
#6      XdrCreateClaimableBalanceOp.decode (package:stellar_flutter_sdk/src/xdr/xdr_account.dart:1078:43)
#7      XdrOperationBody.decode (package:stellar_flutter_sdk/src/xdr/xdr_operation.dart:421:85)
#8      XdrOperation.decode (package:stellar_flutter_sdk/src/xdr/xdr_operation.dart:140:46)
#9      XdrTransaction.decode (package:stellar_flutter_sdk/src/xdr/<…>
```

[Stellar Lab](https://laboratory.stellar.org/#xdr-viewer?input=AAAAAgAAAABGmZyYeYjKxpmwZv1hTKWY5Uc5pzHr7Ld2Tg9KZlXJ2gAAnEAAA588AAAAAwAAAAAAAAABAAAACVBVUnxSVURZMgAAAAAAAAQAAAABAAAAAIw4P8JGqI0p0eawiPOSVAgxDEoyfX71XxIuCEWAAtgeAAAAEAAAAABGmZyYeYjKxpmwZv1hTKWY5Uc5pzHr7Ld2Tg9KZlXJ2gAAAAEAAAAAWN3OP2d8s6y4UvUHUsTnvMLoMY9GcBsYEZA%2FjVvq5l8AAAABAAAAAEaZnJh5iMrGmbBm%2FWFMpZjlRzmnMevst3ZOD0pmVcnaAAAAAlVTRFBFTkQAAAAAAAAAAABY3c4%2FZ3yzrLhS9QdSxOe8wugxj0ZwGxgRkD%2BNW%2BrmXwAAAAAF9eEAAAAAAQAAAABGmZyYeYjKxpmwZv1hTKWY5Uc5pzHr7Ld2Tg9KZlXJ2gAAAA4AAAACVVNEUEVORAAAAAAAAAAAAFjdzj9nfLOsuFL1B1LE57zC6DGPRnAbGBGQP41b6uZfAAAAAAX14QAAAAACAAAAAAAAAABGmZyYeYjKxpmwZv1hTKWY5Uc5pzHr7Ld2Tg9KZlXJ2gAAAAAAAAAAAAAAAFjdzj9nfLOsuFL1B1LE57zC6DGPRnAbGBGQP41b6uZfAAAAAwAAAAEAAAAEAAAAAGGedecAAAABAAAAAEaZnJh5iMrGmbBm%2FWFMpZjlRzmnMevst3ZOD0pmVcnaAAAAEQAAAAAAAAAA&type=TransactionEnvelope&network=test)

**Comment by christian-rogobete** [comment]
Hello @flyweight thank you for adding this issue. There was a bug in the xdr parsing. I fixed in [release 1.2.5](https://github.com/Soneso/stellar_flutter_sdk/releases/tag/1.2.5)
