### ISSUE TITLE
SEP-10 timebounds are checked incorrectly

### ISSUE THREAD

**Issue by Nopik** [Soneso/stellar_flutter_sdk#36]
Hello,

It seems that the timebounds in SEP-10 challenge transaction are checked incorrectly. The timebounds are expressed in seconds, but they are compared with `currentTime` variable, expressed in milliseconds, causing exception to be thrown.

It can be seen in debugger: 
![image](https://user-images.githubusercontent.com/554841/143625543-fab20bcc-d07f-47f1-a2ac-ba89abb5e894.png)

The relevant code is here:
https://github.com/Soneso/stellar_flutter_sdk/blob/bcfa69776803c34df82204a4af7e42223e210a3c/lib/src/sep/0010/webauth.dart#L216-L230

The JS SDK does `/1000` properly: https://github.com/stellar/js-stellar-sdk/blob/c09f8f5b789dd596531ba334fd0b9e19f0265933/src/utils.ts#L735

**Comment by christian-rogobete** [comment]
Hello @Nopik thank you for adding this issue. I fixed it in [release 1.2.6](https://github.com/Soneso/stellar_flutter_sdk/releases/tag/1.2.6)

**Comment by Nopik** [comment]
Thanks! That solves the issue, but actually opens another one. I'll file new issue.
