### ISSUE TITLE
Unable to obtain JWT token from nTokens staging server

### ISSUE THREAD

**Issue by Nopik** [Soneso/stellar_flutter_sdk#37]
Hello,
With the 1.2.6 SDK, I'm trying following code to obtain JWT from nTokens staging server:

```
    const anchorDomain = 'staging.ntokens.com';
    final toml = await StellarToml.fromDomain(anchorDomain);

    final webAuth = WebAuth(
      toml.generalInformation?.webAuthEndpoint,
      Network.TESTNET,
      toml.generalInformation?.signingKey,
      anchorDomain,
    );

    final jwt = await webAuth.jwtToken(accountId, [keypair]);
```

and while equivalent code works on backend (JS SDK), I'm receiving error from https://github.com/Soneso/stellar_flutter_sdk/blob/bcfa69776803c34df82204a4af7e42223e210a3c/lib/src/sep/0010/webauth.dart#L282:

```
{\"detail\":\"Unsupported media type \\"text/plain; charset=utf-8\\" in request.\"}
```

Can you please make sure that the Flutter SDK works with the nTokens server? I'm not sure if the problem is on the Flutter SDK side, or nTokens are too restrictive.

**Comment by christian-rogobete** [comment]
Hi @Nopik, I committed a potential fix: https://github.com/Soneso/stellar_flutter_sdk/commit/989964116137fab84459c7c731098f002650bb27
Can you pls. test if it works with that and let me know?

**Comment by Nopik** [comment]
@christian-rogobete so, it changed something. Now the server responds with: `{\"detail\":\"JSON parse error - Expecting value: line 1 column 1 (char 0)\"}`.

**Comment by Nopik** [comment]
The body being sent seems valid: https://laboratory.stellar.org/#xdr-viewer?input=AAAAAgAAAADCJEP%2B4WNwqXHn8bDhO8ptn3t3d7ixSw1W76%2BS3mmYpwAAAMgAAAAAAAAAAAAAAAEAAAAAYaI2MQAAAABhojm1AAAAAAAAAAIAAAABAAAAAGwyFuYpS8T0b8tAEGWTC9dx7QyWwydi7wK1iNC%2FGUzDAAAACgAAABhzdGFnaW5nLm50b2tlbnMuY29tIGF1dGgAAAABAAAAQG1RTkpzOUt6cFJYeHBwMlRrWlEzdmZ5N0E5emo2YWNFMWc4bGFUL1lHOTJ6L3lJelZQbS8yZHdVbVFtNXE1WC8AAAABAAAAAMIkQ%2F7hY3CpcefxsOE7ym2fe3d3uLFLDVbvr5LeaZinAAAACgAAAA93ZWJfYXV0aF9kb21haW4AAAAAAQAAABNzdGFnaW5nLm50b2tlbnMuY29tAAAAAAAAAAAC3mmYpwAAAECvHgdgcK7B9acr9pQ8cGaq2YYqoETdr6wkiUW%2F9ravbu7nQMvr0qoB8pATevSs3CiWPkmFF7SNUM4Ne3lyQTYFvxlMwwAAAEA%2FiHIOZ%2Bhqt%2BMFJB3yL%2FJrt0fTJ852K635WrEtFgHZ21Kd1HWviA9iufL%2Fi84QYFW79x4jSCVJQl%2BGNwhg1DwL&type=TransactionEnvelope&network=test

**Comment by christian-rogobete** [comment]
I think it needs to be json like: {transaction="AAA..."},one moment

**Comment by christian-rogobete** [comment]
@Nopik can you please try it again? https://github.com/Soneso/stellar_flutter_sdk/commit/b21749bc27e4f43d76b98b5efec81632c9746a4d

**Comment by Nopik** [comment]
@christian-rogobete It would really be more efficient if you would try to run this code yourself. Exception: `Bad state: Cannot set the body fields of a Request with content-type "application/json".`

**Comment by Nopik** [comment]
Adding `json.encode()` solves that problem (`body: json.encode({"transaction": base64EnvelopeXDR})`), and now JWT token is obtained properly. Please release the 1.2.7 with those changes

**Comment by christian-rogobete** [comment]
@Nopik try it one more time please with the latest commit. I think it will solve the problem too. Pls. let me know

**Comment by Nopik** [comment]
@christian-rogobete please see my previous problem. If I leave the `json.encode` in place, but remove the headers like in your last commit, the original problem (Invalid media type) appears again.

**Comment by christian-rogobete** [comment]
ok, I need to fix the test too first. This is your code, right
![Screenshot 2021-11-27 at 15 08 43](https://user-images.githubusercontent.com/35729606/143684943-b07d5322-83b0-4671-8727-14dfb791e673.png)
?

**Comment by Nopik** [comment]
@christian-rogobete yes, that is my code now, it works for me.

**Comment by christian-rogobete** [comment]
ok, I will fix the test and the release a new version, thx

**Comment by Nopik** [comment]
Great, thanks.

**Comment by christian-rogobete** [comment]
yw see [release 1.2.7](https://github.com/Soneso/stellar_flutter_sdk/releases/tag/1.2.7)

**Comment by Nopik** [comment]
It works, thanks.
