### ISSUE TITLE
Exception Submitting transaction 

### ISSUE THREAD

**Issue by abidnazir27** [Soneso/stellar_flutter_sdk#38]
Hi,
I'm getting this exception after withdraw request when trying to deposit to anchor.

Exception: Bad state: Cannot set the body fields of a Request with content-type "application/json".
E/flutter ( 8436): #0      Request.bodyFields= (package:http/src/request.dart:133:7)
E/flutter ( 8436): #1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:87:17)
E/flutter ( 8436): #2      BaseClient.post (package:http/src/base_client.dart:32:7)
E/flutter ( 8436): #3      StellarSDK.submitTransactionEnvelopeXdrBase64 (package:stellar_flutter_sdk/src/stellar_sdk.dart:160:10)
E/flutter ( 8436): #4      StellarSDK.submitTransaction (package:stellar_flutter_sdk/src/stellar_sdk.dart:141:12)

`Asset asset = AssetTypeCreditAlphaNum4('SRT' , issuer);`

`Transaction transaction = TransactionBuilder(sender)
.addOperation(PaymentOperationBuilder(
withdrawAnchorAccount,
asset,'100')
.build()).addMemo(MemoHash(base64Decode(withdrawMemo)))
.build();`

`transaction.sign(keyPair,Network.TESTNET);`
`SubmitTransactionResponse submitTransactionResponse = await StellarSDK.TESTNET.submitTransaction(transaction);`

**Comment by christian-rogobete** [comment]
Hello @abidnazir27,
thank you for reporting this issue. I tried to reproduce the issue, but no luck. 
You can see the corresponding test in my latest commit: https://github.com/Soneso/stellar_flutter_sdk/commit/4ace040a6e04036d9c7c05f486ef113d1a91975f
in test/payments_test.dart

Do you still have the issue? 
If yes, which version of the SDK are you using?
Did you change the httpClient of StellarSDK? E.g. by setting it or by adding a content type header with the value of "application/json"?

**Comment by abidnazir27** [comment]
Yes Still have the issue.
I'm using Stellar SDK 1.2.7
In stellar_sdk.dart  -> submitTransactionEnvelopeXdrBase64 method If I remove Content-Type from Headers then it works fine.
`if(RequestBuilder.headers.containsKey("Content-Type")) {`
     ` RequestBuilder.headers.removeWhere((key, value) => key == 'Content-Type');`
   ` }`
<img width="470" alt="Capture" src="https://user-images.githubusercontent.com/24955466/148888676-d958f3c1-450a-45c7-bf88-f1c222c8e4cd.PNG">


Have you tried to deposit an amount to anchor after withdrawal request ? This is where I'm getting the issue.

**Comment by christian-rogobete** [comment]
thank you @abidnazir27,
I fixed it in [release 1.2.8](https://github.com/Soneso/stellar_flutter_sdk/releases/tag/1.2.8) 
should work now

**Comment by abidnazir27** [comment]
Thank You @christian-rogobete
It's working now.
