### ISSUE TITLE
Issues in the example code

### ISSUE THREAD

**Issue by gbbest15** [Soneso/stellar_flutter_sdk#46]
after running the example code to create account i keep getting this error...

```
E/flutter (28206): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Error response from the server. Code: 404 - Body: {
E/flutter (28206):   "type": "https://stellar.org/horizon-errors/not_found",
E/flutter (28206):   "title": "Resource Missing",
E/flutter (28206):   "status": 404,
E/flutter (28206):   "detail": "The resource at the url requested was not found.  This usually occurs for one of two reasons:  The url requested is not valid, or no data in our database could be found with the parameters provided."
```

**Comment by christian-rogobete** [comment]
hey @gbbest15 do you still have this problem? It seams that you had no internet connection.

**Comment by gbbest15** [comment]
@christian-rogobete not yet, i have internet connected.. the project is weekend project.. i will look into it this weekend...

**Comment by christian-rogobete** [comment]
great, thanks, pls. consider that the accountIds used in the examples are old and may not exist any more on the test net. there is a testnet reset every 3 month
