### ISSUE TITLE
Get asset code from offers

### ISSUE THREAD

**Issue by AliKarimiENT** [Soneso/stellar_flutter_sdk#47]
Hello 
I have faced an issue: I can not get Selling and Buying asset's code from offers of an account.
For example, I have created an offer from native to BTC. When I load the offers, there is no property to get the asset's code.
Please check this 
Thanks

**Comment by AliKarimiENT** [comment]
This actually is in Asset class that there is nothing to get asset code
![image](https://user-images.githubusercontent.com/57004354/188958065-d5909335-08db-4285-a1ba-8572b0295e49.png)

**Comment by Kanaye** [comment]
Well I don't know flutter so take everthing with a grain of salt but you won't find that field in the `Asset` base class as ... not all assets have a code. XLM/native is also an asset, but none with an issuer or code. 
So you'll need to test if the asset is an ALPANUMARIC asset and 🎉 you'll find the code and issuer properties.
https://github.com/Soneso/stellar_flutter_sdk/blob/61f48613baf5baf904999f548adcff1e72b35184/lib/src/asset_type_credit_alphanum.dart#L11-L12

**Comment by AliKarimiENT** [comment]
Thanks, I defined these variables
late stl.AssetTypeCreditAlphaNum sellingAsset,buyingAsset;
And initialized with a cast to AssetTypeCreditAlphaNum
sellingAsset = offer.selling as stl.AssetTypeCreditAlphaNum;
