### ISSUE TITLE
Update the `toml` package to the latest version

### ISSUE THREAD

**Issue by Maadhav** [Soneso/stellar_flutter_sdk#48]
I just upgraded to the latest version of flutter and there seems to be some syntax errors being detected when trying to build, I am quite sure, it is due to the old version of the `toml` package used.

Is there any specific reason why it's not updated?

Current Version: `toml: ^0.11.0`
New Version: `toml: ^0.13.1`

**Comment by christian-rogobete** [comment]
Hi @Maadhav,
thank you for adding this issue. I updated the dependency packages to their newest versions. 
Pls. check it and let me know if it solves your issue. 
[release 1.3.7](https://github.com/Soneso/stellar_flutter_sdk/releases/tag/1.3.7)

**Comment by Maadhav** [comment]
Yes it fixed the issue.

Thank you very much
