### ISSUE TITLE
_ClientSocketException

### ISSUE THREAD

**Issue by jopmiddelkamp** [Soneso/stellar_flutter_sdk#67]
We are seeing a lot of errors in our crashlytics.. First I thought it has to do with bad signal but we never see any issue/exceptions with our Dio requests.. I wonder if you might have any ideas?

<img width="513" alt="Screenshot 2023-07-20 at 20 24 04" src="https://github.com/Soneso/stellar_flutter_sdk/assets/1774351/0096c2c9-6234-4bf3-acc2-9e0ccdb12898">
<img width="524" alt="Screenshot 2023-07-20 at 20 23 51" src="https://github.com/Soneso/stellar_flutter_sdk/assets/1774351/368f66e4-62db-4714-bcd0-b21408a1aa27">

**Comment by hasToDev** [comment]
`Failed host lookup` error usually has something to do with no internet connection.
`fromDomain` did not handle the error thrown by the HTTP client.
For now, catch the error thrown by `fromDomain` and retry again.

**Comment by jopmiddelkamp** [comment]
My bad, somehow we refactored away some code that stops the pulling process in the background. This error has to do with pulling in the background.
