### ISSUE TITLE
 Restructuring SEP-9 Fields: Separating Financial Account Fields

### ISSUE THREAD

**Issue by ydag** [Soneso/stellar_flutter_sdk#86]
The current SDK implementation comprises Natural Person Fields, represented by `NaturalPersonKYCFields`, and Organization Fields, represented by `OrganizationKYCFields`. However, it lacks a dedicated standalone object for Financial Account Fields, as these are currently incorporated as related fields within `NaturalPersonKYCFields`.

As per the evolving requirements and the recent update in the SEP-6 protocol, there is a need to restructure SEP-9 fields to include dedicated Financial Account Fields.

### Proposed Changes:

1. Introduce a new class `FinancialAccountFields` to represent [SEP-9 Financial Account Fields](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0009.md#financial-account-fields).
2. Utilize this new class to request or provide information about off-chain financial account within `NaturalPersonKYCFields` and `OrganizationKYCFields`.
3. Clearly define the organization. prefix usage when requesting or providing fields related to an organization as mentioned in the protocol.

With these changes, we will be able to support the recent updates in the SEP-6 protocol which is proposed as #87, enhancing the SDK's compatibility and providing better flexibility to handle a diverse range of financial account information for both natural persons and organizations.

**Comment by christian-rogobete** [comment]
Hello @ydag, thank you for adding this issue. I resolved it in [release 1.7.5](https://github.com/Soneso/stellar_flutter_sdk/releases/tag/1.7.5)
