### ISSUE TITLE
Improvement to the package

### ISSUE THREAD

**Issue by iampawan** [Soneso/stellar_flutter_sdk#88]
Hi, I was looking to implement the package but I can see that the code quality is not so good and it unnecessarily uses the Flutter SDK, which it should not depend on. I am willing to contribute if you approve of fixing all these. So let me know your thoughts about it.

**Comment by christian-rogobete** [comment]
Hi @iampawan thank you for your offer. It would be great if you could help to improve the SDK. What do you need to get started?

**Comment by iampawan** [comment]
Hi @christian-rogobete, thanks for your response. First of all thanks for doing an awesome job. I have done lots of refactoring on this package which I can add back to the original package. What are your thoughts on merging both packages (this one and the wallet one) together as I feel they could be part of a single package? Also, removing the flutter SDK dependency as there are no widgets.

**Comment by christian-rogobete** [comment]
Hi @iampawan thank you for your message. Can you please create a pull request with your improvements? As far as the wallet SDK is concerned, it has a different purpose and I would like to keep it as a separate project. It is based on a standard defined by SDF for the [Stellar Wallet SDKs](https://stellar.org/products-and-tools/wallet-sdk). See also the official [docs](https://developers.stellar.org/docs/category/build-a-wallet-with-the-wallet-sdk).
