### ISSUE TITLE
Tor/SOCKS5 proxy support

### ISSUE THREAD

**Issue by sneurlax** [Soneso/stellar_flutter_sdk#91]
Hi, I'm adding optional Tor/SOCKS5 proxy support to stellar_flutter_sdk and would like to contribute this feature back upstream.

I'm approaching it by focusing on the HttpClient in https://github.com/Soneso/stellar_flutter_sdk/blob/33c12d7a3f0ef3486707dea5884ac6cd4459bbb9/lib/src/stellar_sdk.dart

Do you have any suggestions or requirements for merging such functionality?

**Comment by sneurlax** [comment]
This week I have so far submitted PRs upstream for

- Solana: https://github.com/espresso-cash/espresso-cash-public/pull/1386
- Tezos: https://github.com/moneytrackio/tezart/pull/103

and will use something akin to either of these approaches here.  Please let me know if you'd like it done in any particular way :)

**Comment by christian-rogobete** [comment]
Sounds good, thank you! Looking forward to your PR!

**Comment by christian-rogobete** [comment]
Done in this [release 1.7.8](https://github.com/Soneso/stellar_flutter_sdk/releases/tag/1.7.8)
