### ISSUE TITLE
[WEB]: tx_bad_seq for any operation on PUBLIC net

### ISSUE THREAD

**Issue by rinat-enikeev** [Soneso/stellar_flutter_sdk#97]
Web!

Steps to reproduce: 

1. clone https://github.com/rinat-enikeev/sfsdk_web_issue
2. run on chrome in release mode
3. press button

Expected: 
Trustline established 

Actual: 
400 tx_bad_seq

```dart
final stellarSDK = StellarSDK.PUBLIC;
    final asset = Asset.createNonNativeAsset(
        'USDC', 'GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN');

    AccountResponse account =
        await stellarSDK.accounts.account(keyPair!.accountId);

    Transaction transaction = TransactionBuilder(account)
        .addOperation(
            ChangeTrustOperationBuilder(asset, '922337203685.4775807').build())
        .build();

    transaction.sign(keyPair!, Network.PUBLIC);

    SubmitTransactionResponse response =
        await stellarSDK.submitTransaction(transaction);
```

<img width="768" alt="Screenshot 2024-07-04 at 22 22 37" src="https://github.com/Soneso/stellar_flutter_sdk/assets/722716/3b0c1f20-c993-4cf2-b406-0426bed6085e">

**Comment by christian-rogobete** [comment]
Resolved in [release 1.8.3](https://github.com/Soneso/stellar_flutter_sdk/releases/tag/1.8.3)

Hello @rinat-enikeev,

thank you for adding this issue and the steps to reproduce. The issue has been solved in  [release 1.8.3](https://github.com/Soneso/stellar_flutter_sdk/releases/tag/1.8.3).

If you find any further issues on web, I would be pleased to receive your further issues. This will help us to provide full web support soon.

Thx C
