### ISSUE TITLE
Fix Mutable Headers in RequestBuilder Causing Errors

### ISSUE THREAD

**Issue by ydag** [Soneso/stellar_flutter_sdk#98]
The RequestBuilder class in the stellar_flutter_sdk library contains a static headers property defined as:

```dart
static final Map<String, String> headers = {
  "X-Client-Name": "stellar_flutter_sdk",
  "X-Client-Version": StellarSDK.versionNumber
};
```

### Problem

The current implementation directly assigns RequestBuilder.headers, creating a reference to the RequestBuilder.headers instead of a new independent variable. Consequently, when the headers are modified in one part of the code, it inadvertently affects all instances, leading to issues such as "Invalid header signature" for some anchors. An example of this improper usage is:

```dart
final Map<String, String> atHeaders = RequestBuilder.headers;
if (jwt != null) {
  atHeaders['Authorization'] = 'Bearer $jwt';
}
```

This issue appears in multiple classes, including : 
- `transfer_server_service.dart`
- `kyc_service.dart`
- `sep24_service.dart`

### Proposed Solution

To resolve this issue, we should make the RequestBuilder.headers an unmodifiable map and ensure that a copy of the headers is created whenever it is used. The proposed changes are as follows:

  1. Make `RequestBuilder.headers` an unmodifiable map:
  ```dart
  static final Map<String, String> headers = Map<String, String>.unmodifiable({
  "X-Client-Name": "stellar_flutter_sdk",
  "X-Client-Version": StellarSDK.versionNumber
});
  ```

  2.Create a copy of `RequestBuilder.headers` whenever it is used:

  ```dart
final Map<String, String> atHeaders = {
  ...RequestBuilder.headers,
  if (jwt != null) "Authorization": "Bearer $jwt",
};
  ```

**Comment by christian-rogobete** [comment]
Resolved in [release 1.8.3](https://github.com/Soneso/stellar_flutter_sdk/releases/tag/1.8.3)
